-- 1. Create table for events (New System)
CREATE TABLE IF NOT EXISTS events (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    date DATE NOT NULL,
    location TEXT NOT NULL,
    description TEXT,
    max_quota INTEGER DEFAULT 100,
    is_active BOOLEAN DEFAULT false
);

-- 2. Create table for registrations
CREATE TABLE IF NOT EXISTS registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    age INTEGER,
    city TEXT,
    instagram_username TEXT,
    
    -- Fields from form
    participation_history TEXT, 
    vest_size TEXT,
    tiktok_proof_url TEXT,
    instagram_proof_url TEXT,
    
    payment_proof_url TEXT,
    event_name TEXT, -- Keeping for backup/display
    event_id UUID REFERENCES events(id), -- Link to specific event
    status TEXT DEFAULT 'pending'
);

-- 3. Legacy settings (Optional, can be removed if fully migrated)
CREATE TABLE IF NOT EXISTS event_settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- 4. Manual Setup Required in Supabase Dashboard:
-- Storage Bucket: Create a new bucket named 'registrations' (Public)

-- 5. DISABLE RLS (For simple access since we use client-side admin auth)
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE registrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_settings DISABLE ROW LEVEL SECURITY;